[package]
name    = "privacyguard-linux"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "privacyguard"

[dependencies]
privacyguard-core = { path = "../privacyguard-core", default-features = false }
tun               = { version = "0.6", features = ["async"] }
tokio             = { version = "1", features = ["full"] }
clap              = { version = "4", features = ["derive"] }
serde             = { version = "1", features = ["derive"] }
serde_json        = "1"
tracing           = "0.1"
tracing-subscriber = "0.3"

[profile.release]
opt-level = 3
lto       = true
strip     = "symbols"
